language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  global:
    - DISPLAY=:99.0
    - CXX=g++-4.8
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "8"
      env: TEST_SUITE=lint
    - os: linux
      node_js: "8"
      env: TEST_SUITE=test
    - os: linux
      node_js: "10"
      env: TEST_SUITE=test
script: npm run $TEST_SUITE
