sudo: false
os:
  - linux
  - osx
language: node_js
node_js:
  - "5"
  - "6"
  - "8"
  - "10"
  - "11"
  - "12"
  - "13"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
env:
  global:
    - JOBS=2
  matrix:
    - TEST_SUITE=unit
matrix:
  fast_finish: true
script: npm run $TEST_SUITE
